name: Build macOS App

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Upgrade pip and install dependencies
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install --use-pep517 setuptools py2app customtkinter tk

      - name: Build application
        run: |
          source venv/bin/activate
          python3 setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: koboldcpp-app
          path: dist/

