name: Koboldcpp Mac x86

on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NOAVX2: 1

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install dependencies
        id: install_dependencies
        run: |
          python3 -m pip install setuptools py2app customtkinter tk

      - name: Build
        id: make_build
        run: |
          python3 setup.py py2app

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: kcpp_mac_app_x86
          path: dist/
